name: .NET

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write

jobs:
  dotnet:

    runs-on: ubuntu-latest

    env:
      IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore src

    - name: Test
      run: dotnet test src --no-restore --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      if: github.event_name == 'pull_request'
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Pack
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      run: dotnet pack src --no-restore -o out -c Release -p:ContinuousIntegrationBuild=true

    - name: Push
      run: dotnet nuget push *.nupkg -s nuget.org -k $NUGET_API_KEY
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
      working-directory: out
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
